battleships::AIHardPlayer
AIStates
The AI is searching for its next target
AIStates battleships.AIHardPlayer._CurrentState
Referenced by battleships.AIHardPlayer.GenerateCoords, battleships.AIHardPlayer.ProcessHit, battleships.AIHardPlayer.ProcessShot, battleships.AIHardPlayer.RemoveShotsAround.
Stack<Target> battleships.AIHardPlayer._Targets
Referenced by battleships.AIHardPlayer.MoveToTopOfStack, battleships.AIHardPlayer.ProcessShot, battleships.AIHardPlayer.RemoveShotsAround.
List<Target> battleships.AIHardPlayer._LastHit
Referenced by battleships.AIHardPlayer.ProcessDestroy.
Target battleships.AIHardPlayer._CurrentTarget
Referenced by battleships.AIHardPlayer.AddTarget, battleships.AIHardPlayer.GenerateCoords, battleships.AIHardPlayer.ProcessDestroy, battleships.AIHardPlayer.ProcessHit, battleships.AIHardPlayer.ProcessShot, battleships.AIHardPlayer.ReOrderTargets, battleships.AIHardPlayer.SearchCoords, battleships.AIHardPlayer.TargetCoords.
battleships.AIHardPlayer.AIHardPlayer(BattleShipsGame game)
override void battleships.AIHardPlayer.GenerateCoords(ref int row, ref int column)
GenerateCoords will call upon the right methods to generate the appropriate shooting coordinates row the row that will be shot at column the column that will be shot at
References battleships.AIHardPlayer._CurrentState, battleships.AIHardPlayer._CurrentTarget, battleships.Player.EnemyGrid, battleships.ISeaGrid.Height, battleships.AIHardPlayer.SearchCoords, battleships.AIHardPlayer.TargetCoords, battleships.ISeaGrid.Width.
override void battleships.AIHardPlayer.ProcessShot(int row, int col, AttackResult result)
ProcessShot is able to process each shot that is made and call the right methods belonging to that shot. For example, if its a miss = do nothing, if it's a hit = process that hit location row the row that was shot at col the column that was shot at result the result from that hit
References battleships.AIHardPlayer._CurrentState, battleships.AIHardPlayer._CurrentTarget, battleships.AIHardPlayer._Targets, battleships.AIHardPlayer.ProcessDestroy, battleships.AIHardPlayer.ProcessHit, battleships.AttackResult.Ship.
void battleships.AIHardPlayer.TargetCoords(ref int row, ref int column)
TargetCoords is used when a ship has been hit and it will try and destroy this ship row row generated around the hit tile column column generated around the hit tile
References battleships.AIHardPlayer._CurrentTarget.
Referenced by battleships.AIHardPlayer.GenerateCoords.
void battleships.AIHardPlayer.SearchCoords(ref int row, ref int column)
SearchCoords will randomly generate shots within the grid as long as its not hit that tile already row the generated row column the generated column
References battleships.AIHardPlayer._CurrentTarget.
Referenced by battleships.AIHardPlayer.GenerateCoords.
void battleships.AIHardPlayer.ProcessDestroy(int row, int col, Ship ship)
ProcessDetroy is able to process the destroyed ships targets and remove _LastHit targets. It will also call RemoveShotsAround to remove targets that it was going to shoot at row the row that was shot at and destroyed col the row that was shot at and destroyed ship the row that was shot at and destroyed
References battleships.AIHardPlayer._CurrentTarget, battleships.AIHardPlayer._LastHit, battleships.AIHardPlayer.RemoveShotsAround, battleships.AIHardPlayer.Target.ShotAt, battleships.AIHardPlayer.Target.Source.
Referenced by battleships.AIHardPlayer.ProcessShot.
void battleships.AIHardPlayer.RemoveShotsAround(Location toRemove)
RemoveShotsAround will remove targets that belong to the destroyed ship by checking if the source of the targets belong to the destroyed ship. If they don't put them on a new stack. Then clear the targets stack and move all the targets that still need to be shot at back onto the targets stack toRemove
References battleships.AIHardPlayer._CurrentState, battleships.AIHardPlayer._Targets, battleships.AIHardPlayer.Target.Source.
Referenced by battleships.AIHardPlayer.ProcessDestroy.
void battleships.AIHardPlayer.ProcessHit(int row, int col)
ProcessHit gets the last hit location coordinates and will ask AddTarget to create targets around that location by calling the method four times each time with a new location around the last hit location. It will then set the state of the AI and if it's not Searching or targetingShip then start ReOrderTargets. row col
References battleships.AIHardPlayer._CurrentState, battleships.AIHardPlayer._CurrentTarget, battleships.AIHardPlayer.AddTarget, battleships.AIHardPlayer.ReOrderTargets.
Referenced by battleships.AIHardPlayer.ProcessShot.
void battleships.AIHardPlayer.ReOrderTargets()
ReOrderTargets will optimise the targeting by re-orderin the stack that the targets are in. By putting the most important targets at the top they are the ones that will be shot at first.
References battleships.AIHardPlayer._CurrentTarget, battleships.AIPlayer.Location.Column, battleships.AIHardPlayer.MoveToTopOfStack, battleships.AIPlayer.Location.Row, battleships.AIHardPlayer.Target.SameColumn, battleships.AIHardPlayer.Target.SameRow, battleships.AIHardPlayer.Target.ShotAt.
Referenced by battleships.AIHardPlayer.ProcessHit.
void battleships.AIHardPlayer.MoveToTopOfStack(int row, int column)
MoveToTopOfStack will re-order the stack by checkin the coordinates of each target If they have the right column or row values it will be moved to the _Match stack else put it on the _NoMatch stack. Then move all the targets from the _NoMatch stack back on the _Targets stack, these will be at the bottom making them less important. The move all the targets from the _Match stack on the _Targets stack, these will be on the top and will there for be shot at first row the row of the optimisation column the column of the optimisation
References battleships.AIHardPlayer._Targets.
Referenced by battleships.AIHardPlayer.ReOrderTargets.
void battleships.AIHardPlayer.AddTarget(int row, int column)
AddTarget will add the targets it will shoot onto a stack row the row of the targets location column the column of the targets location
References battleships.AIHardPlayer._CurrentTarget, battleships.Player.EnemyGrid, battleships.ISeaGrid.Height, battleships.AIHardPlayer.Target.ShotAt, battleships.ISeaGrid.Width.
Referenced by battleships.AIHardPlayer.ProcessHit.