battleships::HighScoreController
const int battleships.HighScoreController.NAME_WIDTH
Referenced by battleships.HighScoreController.LoadScores, battleships.HighScoreController.ReadHighScore.
const int battleships.HighScoreController.SCORES_LEFT
Referenced by battleships.HighScoreController.DrawHighScores, battleships.HighScoreController.ReadHighScore.
List<Score> battleships.HighScoreController._Scores
Referenced by battleships.HighScoreController.DrawHighScores, battleships.HighScoreController.ReadHighScore, battleships.HighScoreController.SaveScores.
static void battleships.HighScoreController.LoadScores()
Loads the scores from the highscores text file. The format is of scores NNNSSSWhere NNN is the name and SSS is the score
References battleships.HighScoreController.NAME_WIDTH.
Referenced by battleships.HighScoreController.DrawHighScores, battleships.HighScoreController.ReadHighScore.
static void battleships.HighScoreController.SaveScores()
Saves the scores back to the highscores text file. The format is of scores NNNSSSWhere NNN is the name and SSS is the score
References battleships.HighScoreController._Scores.
static void battleships.HighScoreController.DrawHighScores()
Draws the high scores to the screen.
References battleships.HighScoreController._Scores, battleships.GameResources.GameFont, battleships.HighScoreController.LoadScores, battleships.HighScoreController.Score.Name, battleships.HighScoreController.SCORES_LEFT, battleships.HighScoreController.Score.Value.
Referenced by battleships.HighScoreController.ReadHighScore.
static void battleships.HighScoreController.HandleHighScoreInput()
Handles the user input during the top score screen.
static void battleships.HighScoreController.ReadHighScore(int value)
Read the user's name for their highsSwinGame. value the player's sSwinGame. This verifies if the score is a highsSwinGame.
References battleships.HighScoreController._Scores, battleships.HighScoreController.DrawHighScores, battleships.HighScoreController.LoadScores, battleships.HighScoreController.NAME_WIDTH, battleships.HighScoreController.SCORES_LEFT.