battleships::MenuController
readonly string [][] battleships.MenuController._menuStructure
The menu structure for the game.
These are the text captions for the menu items.
Referenced by battleships.MenuController.DrawButtons, battleships.MenuController.HandleMenuInput.
readonly Color battleships.MenuController.MENU_COLOR
Referenced by battleships.MenuController.DrawButtons.
readonly Color battleships.MenuController.HIGHLIGHT_COLOR
Referenced by battleships.MenuController.DrawButtons.
const int battleships.MenuController.MENU_TOP
Referenced by battleships.MenuController.DrawButtons, battleships.MenuController.IsMouseOverMenu.
const int battleships.MenuController.MENU_LEFT
Referenced by battleships.MenuController.DrawButtons, battleships.MenuController.IsMouseOverMenu.
const int battleships.MenuController.MENU_GAP
Referenced by battleships.MenuController.DrawButtons, battleships.MenuController.IsMouseOverMenu.
const int battleships.MenuController.BUTTON_WIDTH
Referenced by battleships.MenuController.DrawButtons, battleships.MenuController.IsMouseOverMenu.
const int battleships.MenuController.BUTTON_HEIGHT
Referenced by battleships.MenuController.DrawButtons, battleships.MenuController.IsMouseOverMenu.
const int battleships.MenuController.BUTTON_SEP
Referenced by battleships.MenuController.DrawButtons, battleships.MenuController.IsMouseOverMenu.
const int battleships.MenuController.TEXT_OFFSET
Referenced by battleships.MenuController.DrawButtons.
const int battleships.MenuController.MAIN_MENU
Referenced by battleships.MenuController.DrawMainMenu, battleships.MenuController.DrawSettings, battleships.MenuController.HandleMainMenuInput, battleships.MenuController.HandleSetupMenuInput, battleships.MenuController.PerformMenuAction.
const int battleships.MenuController.GAME_MENU
Referenced by battleships.MenuController.DrawGameMenu, battleships.MenuController.HandleGameMenuInput, battleships.MenuController.PerformMenuAction.
const int battleships.MenuController.SETUP_MENU
Referenced by battleships.MenuController.DrawSettings, battleships.MenuController.HandleSetupMenuInput, battleships.MenuController.PerformMenuAction.
const int battleships.MenuController.MAIN_MENU_PLAY_BUTTON
Referenced by battleships.MenuController.PerformMainMenuAction.
const int battleships.MenuController.MAIN_MENU_SETUP_BUTTON
Referenced by battleships.MenuController.PerformMainMenuAction.
const int battleships.MenuController.MAIN_MENU_TOP_SCORES_BUTTON
Referenced by battleships.MenuController.PerformMainMenuAction.
const int battleships.MenuController.MAIN_MENU_QUIT_BUTTON
Referenced by battleships.MenuController.PerformMainMenuAction.
const int battleships.MenuController.SETUP_MENU_EASY_BUTTON
Referenced by battleships.MenuController.PerformSetupMenuAction.
const int battleships.MenuController.SETUP_MENU_MEDIUM_BUTTON
Referenced by battleships.MenuController.PerformSetupMenuAction.
const int battleships.MenuController.SETUP_MENU_HARD_BUTTON
Referenced by battleships.MenuController.PerformSetupMenuAction.
const int battleships.MenuController.SETUP_MENU_EXIT_BUTTON
const int battleships.MenuController.GAME_MENU_RETURN_BUTTON
Referenced by battleships.MenuController.PerformGameMenuAction.
const int battleships.MenuController.GAME_MENU_SURRENDER_BUTTON
Referenced by battleships.MenuController.PerformGameMenuAction.
const int battleships.MenuController.GAME_MENU_QUIT_BUTTON
Referenced by battleships.MenuController.PerformGameMenuAction.
static void battleships.MenuController.HandleMainMenuInput()
Handles the processing of user input when the main menu is showing
References battleships.MenuController.HandleMenuInput, battleships.MenuController.MAIN_MENU.
static void battleships.MenuController.HandleSetupMenuInput()
Handles the processing of user input when the main menu is showing
References battleships.MenuController.HandleMenuInput, battleships.MenuController.MAIN_MENU, battleships.MenuController.SETUP_MENU.
static void battleships.MenuController.HandleGameMenuInput()
Handle input in the game menu.
Player can return to the game, surrender, or quit entirely
References battleships.MenuController.GAME_MENU, battleships.MenuController.HandleMenuInput.
static void battleships.MenuController.DrawMainMenu()
Draws the main menu to the screen.
References battleships.MenuController.DrawButtons, battleships.MenuController.MAIN_MENU.
static void battleships.MenuController.DrawGameMenu()
Draws the Game menu to the screen
References battleships.MenuController.DrawButtons, battleships.MenuController.GAME_MENU.
static void battleships.MenuController.DrawSettings()
Draws the settings menu to the screen.
Also shows the main menu
References battleships.MenuController.DrawButtons, battleships.MenuController.MAIN_MENU, battleships.MenuController.SETUP_MENU.
static bool battleships.MenuController.HandleMenuInput(int menu, int level, int xOffset)
Handles input for the specified menu.
menu the identifier of the menu being processed level the vertical level of the menu xOffset the xoffset of the menu false if a clicked missed the buttons. This can be used to check prior menus.
References battleships.MenuController._menuStructure, battleships.MenuController.IsMouseOverMenu, battleships.MenuController.PerformMenuAction.
Referenced by battleships.MenuController.HandleGameMenuInput, battleships.MenuController.HandleMainMenuInput, battleships.MenuController.HandleSetupMenuInput.
static void battleships.MenuController.DrawButtons(int menu)
Draw the buttons associated with a top level menu.
menu the index of the menu to draw
Referenced by battleships.MenuController.DrawGameMenu, battleships.MenuController.DrawMainMenu, battleships.MenuController.DrawSettings.
static void battleships.MenuController.DrawButtons(int menu, int level, int xOffset)
Draws the menu at the indicated level.
menu the menu to draw level the level (height) of the menu xOffset the offset of the menu The menu text comes from the _menuStructure field. The level indicates the height of the menu, to enable sub menus. The xOffset repositions the menu horizontally to allow the submenus to be positioned correctly.
References battleships.MenuController._menuStructure, battleships.MenuController.BUTTON_HEIGHT, battleships.MenuController.BUTTON_SEP, battleships.MenuController.BUTTON_WIDTH, battleships.MenuController.HIGHLIGHT_COLOR, battleships.MenuController.IsMouseOverMenu, battleships.MenuController.MENU_COLOR, battleships.MenuController.MENU_GAP, battleships.MenuController.MENU_LEFT, battleships.MenuController.MENU_TOP, battleships.MenuController.TEXT_OFFSET.
static bool battleships.MenuController.IsMouseOverButton(int button)
Determined if the mouse is over one of the button in the main menu.
button the index of the button to check true if the mouse is over that button
References battleships.MenuController.IsMouseOverMenu.
static bool battleships.MenuController.IsMouseOverMenu(int button, int level, int xOffset)
Checks if the mouse is over one of the buttons in a menu.
button the index of the button to check level the level of the menu xOffset the xOffset of the menu true if the mouse is over the button
References battleships.MenuController.BUTTON_HEIGHT, battleships.MenuController.BUTTON_SEP, battleships.MenuController.BUTTON_WIDTH, battleships.MenuController.MENU_GAP, battleships.MenuController.MENU_LEFT, battleships.MenuController.MENU_TOP.
Referenced by battleships.MenuController.DrawButtons, battleships.MenuController.HandleMenuInput, battleships.MenuController.IsMouseOverButton.
static void battleships.MenuController.PerformMenuAction(int menu, int button)
A button has been clicked, perform the associated action.
menu the menu that has been clicked button the index of the button that was clicked
References battleships.MenuController.GAME_MENU, battleships.MenuController.MAIN_MENU, battleships.MenuController.PerformGameMenuAction, battleships.MenuController.PerformMainMenuAction, battleships.MenuController.PerformSetupMenuAction, battleships.MenuController.SETUP_MENU.
Referenced by battleships.MenuController.HandleMenuInput.
static void battleships.MenuController.PerformMainMenuAction(int button)
The main menu was clicked, perform the button's action.
button the button pressed
References battleships.MenuController.MAIN_MENU_PLAY_BUTTON, battleships.MenuController.MAIN_MENU_QUIT_BUTTON, battleships.MenuController.MAIN_MENU_SETUP_BUTTON, battleships.MenuController.MAIN_MENU_TOP_SCORES_BUTTON.
Referenced by battleships.MenuController.PerformMenuAction.
static void battleships.MenuController.PerformSetupMenuAction(int button)
The setup menu was clicked, perform the button's action.
button the button pressed
References battleships.MenuController.SETUP_MENU_EASY_BUTTON, battleships.MenuController.SETUP_MENU_HARD_BUTTON, battleships.MenuController.SETUP_MENU_MEDIUM_BUTTON.
Referenced by battleships.MenuController.PerformMenuAction.
static void battleships.MenuController.PerformGameMenuAction(int button)
The game menu was clicked, perform the button's action.
button the button pressed
References battleships.MenuController.GAME_MENU_QUIT_BUTTON, battleships.MenuController.GAME_MENU_RETURN_BUTTON, battleships.MenuController.GAME_MENU_SURRENDER_BUTTON.
Referenced by battleships.MenuController.PerformMenuAction.