battleships::AIMediumPlayer
AIStates
AIStates battleships.AIMediumPlayer._CurrentState
Referenced by battleships.AIMediumPlayer.GenerateCoords, battleships.AIMediumPlayer.ProcessShot, battleships.AIMediumPlayer.TargetCoords.
Stack<Location> battleships.AIMediumPlayer._Targets
Referenced by battleships.AIMediumPlayer.TargetCoords.
battleships.AIMediumPlayer.AIMediumPlayer(BattleShipsGame controller)
override void battleships.AIMediumPlayer.GenerateCoords(ref int row, ref int column)
GenerateCoordinates should generate random shooting coordinates only when it has not found a ship, or has destroyed a ship and needs new shooting coordinates
row the generated row column the generated column
References battleships.AIMediumPlayer._CurrentState, battleships.Player.EnemyGrid, battleships.ISeaGrid.Height, battleships.AIMediumPlayer.SearchCoords, battleships.AIMediumPlayer.TargetCoords, battleships.ISeaGrid.Width.
override void battleships.AIMediumPlayer.ProcessShot(int row, int col, AttackResult result)
ProcessShot will be called uppon when a ship is found. It will create a stack with targets it will try to hit. These targets will be around the tile that has been hit.
row the row it needs to process col the column it needs to process result the result of the last shot (should be hit)
References battleships.AIMediumPlayer._CurrentState, battleships.AIMediumPlayer.AddTarget, battleships.AttackResult.Value.
void battleships.AIMediumPlayer.TargetCoords(ref int row, ref int column)
TargetCoords is used when a ship has been hit and it will try and destroy this ship
row row generated around the hit tile column column generated around the hit tile
References battleships.AIMediumPlayer._CurrentState, battleships.AIMediumPlayer._Targets.
Referenced by battleships.AIMediumPlayer.GenerateCoords.
void battleships.AIMediumPlayer.SearchCoords(ref int row, ref int column)
SearchCoords will randomly generate shots within the grid as long as its not hit that tile already
row the generated row column the generated column
Referenced by battleships.AIMediumPlayer.GenerateCoords.
void battleships.AIMediumPlayer.AddTarget(int row, int column)
AddTarget will add the targets it will shoot onto a stack
row the row of the targets location column the column of the targets location
References battleships.Player.EnemyGrid, battleships.ISeaGrid.Height, battleships.ISeaGrid.Width.
Referenced by battleships.AIMediumPlayer.ProcessShot.