battleships::UtilityFunctions
const int battleships.UtilityFunctions.FIELD_TOP
Referenced by battleships.UtilityFunctions.AddAnimation, battleships.DiscoveryController.DoAttack, battleships.DeploymentController.DoDeployClick, battleships.UtilityFunctions.DrawField.
const int battleships.UtilityFunctions.FIELD_LEFT
Referenced by battleships.UtilityFunctions.AddAnimation, battleships.DiscoveryController.DoAttack, battleships.DeploymentController.DoDeployClick, battleships.UtilityFunctions.DrawField, battleships.UtilityFunctions.DrawMessage.
const int battleships.UtilityFunctions.FIELD_WIDTH
Referenced by battleships.UtilityFunctions.DrawField.
const int battleships.UtilityFunctions.FIELD_HEIGHT
Referenced by battleships.UtilityFunctions.DrawField.
const int battleships.UtilityFunctions.MESSAGE_TOP
Referenced by battleships.UtilityFunctions.DrawMessage.
const int battleships.UtilityFunctions.CELL_WIDTH
Referenced by battleships.UtilityFunctions.AddAnimation, battleships.DiscoveryController.DoAttack, battleships.DeploymentController.DoDeployClick, battleships.UtilityFunctions.DrawField.
const int battleships.UtilityFunctions.CELL_HEIGHT
Referenced by battleships.UtilityFunctions.AddAnimation, battleships.DiscoveryController.DoAttack, battleships.DeploymentController.DoDeployClick, battleships.UtilityFunctions.DrawField.
const int battleships.UtilityFunctions.CELL_GAP
Referenced by battleships.UtilityFunctions.AddAnimation, battleships.DiscoveryController.DoAttack, battleships.DeploymentController.DoDeployClick, battleships.UtilityFunctions.DrawField.
const int battleships.UtilityFunctions.SHIP_GAP
Referenced by battleships.UtilityFunctions.DrawCustomField.
const int battleships.UtilityFunctions.ANIMATION_CELLS
Referenced by battleships.UtilityFunctions.DrawAnimationSequence.
const int battleships.UtilityFunctions.FRAMES_PER_CELL
Referenced by battleships.UtilityFunctions.DrawAnimationSequence.
readonly Color battleships.UtilityFunctions.SMALL_SEA
Referenced by battleships.UtilityFunctions.DrawCustomField.
readonly Color battleships.UtilityFunctions.SMALL_SHIP
readonly Color battleships.UtilityFunctions.SMALL_MISS
Referenced by battleships.UtilityFunctions.DrawCustomField.
readonly Color battleships.UtilityFunctions.SMALL_HIT
Referenced by battleships.UtilityFunctions.DrawCustomField.
readonly Color battleships.UtilityFunctions.LARGE_SEA
readonly Color battleships.UtilityFunctions.LARGE_SHIP
readonly Color battleships.UtilityFunctions.LARGE_MISS
Referenced by battleships.UtilityFunctions.DrawCustomField.
readonly Color battleships.UtilityFunctions.LARGE_HIT
Referenced by battleships.UtilityFunctions.DrawCustomField.
readonly Color battleships.UtilityFunctions.OUTLINE_COLOR
Referenced by battleships.UtilityFunctions.DrawCustomField.
readonly Color battleships.UtilityFunctions.SHIP_FILL_COLOR
Referenced by battleships.UtilityFunctions.DrawCustomField.
readonly Color battleships.UtilityFunctions.SHIP_OUTLINE_COLOR
Referenced by battleships.UtilityFunctions.DrawCustomField.
readonly Color battleships.UtilityFunctions.MESSAGE_COLOR
Referenced by battleships.UtilityFunctions.DrawMessage.
string battleships.UtilityFunctions._message
List<Sprite> battleships.UtilityFunctions._Animations
Referenced by battleships.UtilityFunctions.DrawAnimations, battleships.UtilityFunctions.UpdateAnimations.
string battleships.UtilityFunctions.Message
The message to display
The message to displayThe message to display
Referenced by battleships.UtilityFunctions.DrawMessage.
static bool battleships.UtilityFunctions.IsMouseInRectangle(int x, int y, int w, int h)
Determines if the mouse is in a given rectangle.
x the x location to check y the y location to check w the width to check h the height to check true if the mouse is in the area checked
Referenced by battleships.DeploymentController.GetShipMouseIsOver, battleships.DeploymentController.HandleDeploymentInput.
static void battleships.UtilityFunctions.DrawField(ISeaGrid grid, Player thePlayer, bool showShips)
Draws a large field using the grid and the indicated player's ships.
grid the grid to draw thePlayer the players ships to show showShips indicates if the ships should be shown
References battleships.UtilityFunctions.CELL_GAP, battleships.UtilityFunctions.CELL_HEIGHT, battleships.UtilityFunctions.CELL_WIDTH, battleships.UtilityFunctions.DrawCustomField, battleships.UtilityFunctions.FIELD_HEIGHT, battleships.UtilityFunctions.FIELD_LEFT, battleships.UtilityFunctions.FIELD_TOP, battleships.UtilityFunctions.FIELD_WIDTH.
static void battleships.UtilityFunctions.DrawSmallField(ISeaGrid grid, Player thePlayer)
Draws a small field, showing the attacks made and the locations of the player's ships
grid the grid to show thePlayer the player to show the ships of
References battleships.UtilityFunctions.DrawCustomField.
static void battleships.UtilityFunctions.DrawMessage()
Draws the message to the screen
References battleships.UtilityFunctions.FIELD_LEFT, battleships.UtilityFunctions.Message, battleships.UtilityFunctions.MESSAGE_COLOR, battleships.UtilityFunctions.MESSAGE_TOP.
static void battleships.UtilityFunctions.DrawBackground()
Draws the background for the current state of the game
References battleships.GameController.CurrentState.
static void battleships.UtilityFunctions.AddExplosion(int row, int col)
References battleships.UtilityFunctions.AddAnimation.
static void battleships.UtilityFunctions.AddSplash(int row, int col)
References battleships.UtilityFunctions.AddAnimation.
static void battleships.UtilityFunctions.UpdateAnimations()
References battleships.UtilityFunctions._Animations.
Referenced by battleships.UtilityFunctions.DrawAnimationSequence.
static void battleships.UtilityFunctions.DrawAnimations()
References battleships.UtilityFunctions._Animations.
static void battleships.UtilityFunctions.DrawAnimationSequence()
References battleships.UtilityFunctions.ANIMATION_CELLS, battleships.UtilityFunctions.FRAMES_PER_CELL, battleships.UtilityFunctions.UpdateAnimations.
static void battleships.UtilityFunctions.DrawCustomField(ISeaGrid grid, Player thePlayer, bool small, bool showShips, int left, int top, int width, int height, int cellWidth, int cellHeight, int cellGap)
Draws the player's grid and ships.
grid the grid to show thePlayer the player to show the ships of small true if the small grid is shown showShips true if ships are to be shown left the left side of the grid top the top of the grid width the width of the grid height the height of the grid cellWidth the width of each cell cellHeight the height of each cell cellGap the gap between the cells
References battleships.Ship.Direction, battleships.Ship.IsDeployed, battleships.UtilityFunctions.LARGE_HIT, battleships.UtilityFunctions.LARGE_MISS, battleships.UtilityFunctions.OUTLINE_COLOR, battleships.Ship.Row, battleships.UtilityFunctions.SHIP_FILL_COLOR, battleships.UtilityFunctions.SHIP_GAP, battleships.UtilityFunctions.SHIP_OUTLINE_COLOR, battleships.Ship.Size, battleships.UtilityFunctions.SMALL_HIT, battleships.UtilityFunctions.SMALL_MISS, battleships.UtilityFunctions.SMALL_SEA.
Referenced by battleships.UtilityFunctions.DrawField, battleships.UtilityFunctions.DrawSmallField.
static void battleships.UtilityFunctions.AddAnimation(int row, int col, string image)
References battleships.UtilityFunctions.CELL_GAP, battleships.UtilityFunctions.CELL_HEIGHT, battleships.UtilityFunctions.CELL_WIDTH, battleships.UtilityFunctions.FIELD_LEFT, battleships.UtilityFunctions.FIELD_TOP.
Referenced by battleships.UtilityFunctions.AddExplosion, battleships.UtilityFunctions.AddSplash.