battleships::AIPlayer
battleships.AIPlayer.AIPlayer(BattleShipsGame game)
override AttackResult battleships.AIPlayer.Attack()
The AI takes its attacks until its go is over.
The result of the last attack
References battleships.AIPlayer.Delay, battleships.AIPlayer.GenerateCoords, battleships.AIPlayer.ProcessShot, battleships.AttackResult.Value.
abstract void battleships.AIPlayer.GenerateCoords(ref int row, ref int column)
Generate a valid row, column to shoot at
row output the row for the next shot column output the column for the next show
Referenced by battleships.AIPlayer.Attack.
abstract void battleships.AIPlayer.ProcessShot(int row, int col, AttackResult result)
The last shot had the following result. Child classes can use this to prepare for the next shot.
result The result of the shot row the row shot col the column shot
Referenced by battleships.AIPlayer.Attack.
void battleships.AIPlayer.Delay()
Wait a short period to simulate the think time
Referenced by battleships.AIPlayer.Attack.