battleships::GameController
BattleShipsGame battleships.GameController._theGame
Referenced by battleships.GameController.CheckAttackResult, battleships.GameController.StartGame.
Player battleships.GameController._human
Referenced by battleships.GameController.EndDeployment, battleships.GameController.StartGame.
AIPlayer battleships.GameController._ai
Referenced by battleships.GameController.EndDeployment, battleships.GameController.StartGame.
Stack<GameState> battleships.GameController._state
AIOption battleships.GameController._aiSetting
Referenced by battleships.GameController.SetDifficulty, battleships.GameController.StartGame.
GameState battleships.GameController.CurrentState
Returns the current state of the game, indicating which screen is currently being used
The current stateThe current state
Referenced by battleships.UtilityFunctions.DrawBackground, battleships.GameController.DrawScreen, battleships.GameController.HandleUserInput.
Player battleships.GameController.HumanPlayer
Returns the human player.
the human playerthe human player
Referenced by battleships.GameController.AttackCompleted, battleships.DiscoveryController.DoAttack, battleships.DeploymentController.DoDeployClick, battleships.DeploymentController.DrawDeployment, battleships.DiscoveryController.DrawDiscovery, battleships.EndingGameController.DrawEndOfGame, battleships.DeploymentController.HandleDeploymentInput.
Player battleships.GameController.ComputerPlayer
Returns the computer player.
the computer playerthe computer player
Referenced by battleships.GameController.CheckAttackResult, battleships.DiscoveryController.DrawDiscovery, battleships.EndingGameController.DrawEndOfGame.
static battleships.GameController.GameController()
static void battleships.GameController.EndGame()
Stops listening to the old game once a new game is started
References battleships.GameController.AttackCompleted, battleships.GameController.GridChanged.
Referenced by battleships.GameController.StartGame.
static void battleships.GameController.GridChanged(object sender, EventArgs args)
Listens to the game grids for any changes and redraws the screen when the grids change
sender the grid that changed args not used
References battleships.GameController.DrawScreen.
Referenced by battleships.GameController.EndGame, battleships.GameController.StartGame.
static void battleships.GameController.PlayHitSequence(int row, int column, bool showAnimation)
Referenced by battleships.GameController.AttackCompleted.
static void battleships.GameController.PlayMissSequence(int row, int column, bool showAnimation)
Referenced by battleships.GameController.AttackCompleted.
static void battleships.GameController.AttackCompleted(object sender, AttackResult result)
Listens for attacks to be completed.
sender the game result the result of the attack Displays a message, plays sound and redraws the screen
References battleships.AttackResult.Column, battleships.GameResources.GameSound, battleships.GameController.HumanPlayer, battleships.Player.IsDestroyed, battleships.GameController.PlayHitSequence, battleships.GameController.PlayMissSequence, battleships.AttackResult.Row.
Referenced by battleships.GameController.EndGame, battleships.GameController.StartGame.
static void battleships.GameController.AIAttack()
Gets the AI to attack.
Checks the attack result once the attack is complete.
References battleships.GameController.CheckAttackResult.
Referenced by battleships.GameController.CheckAttackResult.
static void battleships.GameController.CheckAttackResult(AttackResult result)
Checks the results of the attack and switches to Ending the Game if the result was game over.
result the result of the last attack Gets the AI to attack if the result switched to the AI player.
References battleships.GameController._theGame, battleships.GameController.AIAttack, battleships.GameController.ComputerPlayer, battleships.BattleShipsGame.Player, battleships.GameController.SwitchState.
Referenced by battleships.GameController.AIAttack, battleships.GameController.Attack.
static void battleships.GameController.StartGame()
Starts a new game.
Creates an AI player based upon the _aiSetting.
References battleships.GameController._ai, battleships.GameController._aiSetting, battleships.GameController._human, battleships.GameController._theGame, battleships.GameController.AddNewState, battleships.GameController.AttackCompleted, battleships.GameController.EndGame, battleships.GameController.GridChanged.
static void battleships.GameController.EndDeployment()
Completes the deployment phase of the game and switches to the battle mode (Discovering state)
This adds the players to the game before switching state.
References battleships.GameController._ai, battleships.GameController._human, battleships.GameController.SwitchState.
static string battleships.GameController.HelloWorld()
static void battleships.GameController.Attack(int row, int col)
Gets the player to attack the indicated row and column.
row the row to attack col the column to attack Checks the attack result once the attack is complete
References battleships.GameController.CheckAttackResult.
static void battleships.GameController.HandleUserInput()
Handles the user SwinGame.
Reads key and mouse input and converts these into actions for the game to perform. The actions performed depend upon the state of the game.
References battleships.GameController.CurrentState.
static void battleships.GameController.DrawScreen()
Draws the current state of the game to the screen.
What is drawn depends upon the state of the game.
References battleships.GameController.CurrentState.
Referenced by battleships.GameController.GridChanged.
static void battleships.GameController.AddNewState(GameState state)
Move the game to a new state. The current state is maintained so that it can be returned to.
state the new game state
Referenced by battleships.GameController.StartGame, battleships.GameController.SwitchState.
static void battleships.GameController.SwitchState(GameState newState)
End the current state and add in the new state.
newState the new state of the game
References battleships.GameController.AddNewState, battleships.GameController.EndCurrentState.
Referenced by battleships.GameController.CheckAttackResult, battleships.GameController.EndDeployment.
static void battleships.GameController.EndCurrentState()
Ends the current state, returning to the prior state
Referenced by battleships.GameController.SwitchState.
static void battleships.GameController.SetDifficulty(AIOption setting)
Sets the difficulty for the next level of the game.
setting the new difficulty level
References battleships.GameController._aiSetting.