battleships::GameResources
Dictionary<string, Bitmap> battleships.GameResources._Images
Referenced by battleships.GameResources.FreeImages, battleships.GameResources.GameImage.
Dictionary<string, Font> battleships.GameResources._Fonts
Referenced by battleships.GameResources.FreeFonts, battleships.GameResources.GameFont.
Dictionary<string, SoundEffect> battleships.GameResources._Sounds
Referenced by battleships.GameResources.FreeSounds, battleships.GameResources.GameSound.
Dictionary<string, Music> battleships.GameResources._Music
Referenced by battleships.GameResources.FreeMusic, battleships.GameResources.GameMusic.
Bitmap battleships.GameResources._Background
Referenced by battleships.GameResources.EndLoadingScreen, battleships.GameResources.PlaySwinGameIntro, battleships.GameResources.ShowLoadingScreen.
Bitmap battleships.GameResources._Animation
Referenced by battleships.GameResources.EndLoadingScreen, battleships.GameResources.ShowLoadingScreen.
Bitmap battleships.GameResources._LoaderFull
Referenced by battleships.GameResources.EndLoadingScreen, battleships.GameResources.ShowLoadingScreen, battleships.GameResources.ShowMessage.
Bitmap battleships.GameResources._LoaderEmpty
Referenced by battleships.GameResources.EndLoadingScreen, battleships.GameResources.ShowLoadingScreen, battleships.GameResources.ShowMessage.
Font battleships.GameResources._LoadingFont
Referenced by battleships.GameResources.EndLoadingScreen, battleships.GameResources.ShowLoadingScreen, battleships.GameResources.ShowMessage.
SoundEffect battleships.GameResources._StartSound
Referenced by battleships.GameResources.EndLoadingScreen, battleships.GameResources.PlaySwinGameIntro, battleships.GameResources.ShowLoadingScreen.
static void battleships.GameResources.LoadFonts()
References battleships.GameResources.NewFont.
Referenced by battleships.GameResources.LoadResources.
static void battleships.GameResources.LoadImages()
References battleships.GameResources.NewImage.
Referenced by battleships.GameResources.LoadResources.
static void battleships.GameResources.LoadSounds()
References battleships.GameResources.NewSound.
Referenced by battleships.GameResources.LoadResources.
static void battleships.GameResources.LoadMusic()
References battleships.GameResources.NewMusic.
Referenced by battleships.GameResources.LoadResources.
static void battleships.GameResources.ShowLoadingScreen()
References battleships.GameResources._Animation, battleships.GameResources._Background, battleships.GameResources._LoaderEmpty, battleships.GameResources._LoaderFull, battleships.GameResources._LoadingFont, battleships.GameResources._StartSound, battleships.GameResources.PlaySwinGameIntro.
Referenced by battleships.GameResources.LoadResources.
static void battleships.GameResources.PlaySwinGameIntro()
References battleships.GameResources._Background, battleships.GameResources._StartSound.
Referenced by battleships.GameResources.ShowLoadingScreen.
static void battleships.GameResources.ShowMessage(string message, int number)
References battleships.GameResources._LoaderEmpty, battleships.GameResources._LoaderFull, battleships.GameResources._LoadingFont.
Referenced by battleships.GameResources.LoadResources.
static void battleships.GameResources.EndLoadingScreen(int width, int height)
References battleships.GameResources._Animation, battleships.GameResources._Background, battleships.GameResources._LoaderEmpty, battleships.GameResources._LoaderFull, battleships.GameResources._LoadingFont, battleships.GameResources._StartSound.
Referenced by battleships.GameResources.LoadResources.
static void battleships.GameResources.NewFont(string fontName, string filename, int size)
Referenced by battleships.GameResources.LoadFonts.
static void battleships.GameResources.NewImage(string imageName, string filename)
Referenced by battleships.GameResources.LoadImages.
static void battleships.GameResources.NewTransparentColorImage(string imageName, string fileName, Color transColor)
Referenced by battleships.GameResources.NewTransparentColourImage.
static void battleships.GameResources.NewTransparentColourImage(string imageName, string fileName, Color transColor)
References battleships.GameResources.NewTransparentColorImage.
static void battleships.GameResources.NewSound(string soundName, string filename)
Referenced by battleships.GameResources.LoadSounds.
static void battleships.GameResources.NewMusic(string musicName, string filename)
Referenced by battleships.GameResources.LoadMusic.
static void battleships.GameResources.FreeFonts()
References battleships.GameResources._Fonts.
Referenced by battleships.GameResources.FreeResources.
static void battleships.GameResources.FreeImages()
References battleships.GameResources._Images.
Referenced by battleships.GameResources.FreeResources.
static void battleships.GameResources.FreeSounds()
References battleships.GameResources._Sounds.
Referenced by battleships.GameResources.FreeResources.
static void battleships.GameResources.FreeMusic()
References battleships.GameResources._Music.
Referenced by battleships.GameResources.FreeResources.
static Font battleships.GameResources.GameFont(string font)
Gets a Font Loaded in the Resources font Name of Font The Font Loaded with this Name
References battleships.GameResources._Fonts.
Referenced by battleships.DiscoveryController.DrawDiscovery, battleships.HighScoreController.DrawHighScores.
static Bitmap battleships.GameResources.GameImage(string image)
Gets an Image loaded in the Resources image Name of image The image loaded with this name
References battleships.GameResources._Images.
static SoundEffect battleships.GameResources.GameSound(string sound)
Gets an sound loaded in the Resources sound Name of sound The sound with this name
References battleships.GameResources._Sounds.
Referenced by battleships.GameController.AttackCompleted.
static Music battleships.GameResources.GameMusic(string music)
Gets the music loaded in the Resources music Name of music The music with this name
References battleships.GameResources._Music.
static void battleships.GameResources.LoadResources()
The Resources Class stores all of the Games Media Resources, such as Images, Fonts Sounds, Music.
References battleships.GameResources.EndLoadingScreen, battleships.GameResources.LoadFonts, battleships.GameResources.LoadImages, battleships.GameResources.LoadMusic, battleships.GameResources.LoadSounds, battleships.GameResources.ShowLoadingScreen, battleships.GameResources.ShowMessage.
static void battleships.GameResources.FreeResources()
References battleships.GameResources.FreeFonts, battleships.GameResources.FreeImages, battleships.GameResources.FreeMusic, battleships.GameResources.FreeSounds.